### PR TITLE
ci: add ios-build.yml to build iOS sample

### LINKED ISSUE #353: Build iOS sample on CI
To ensure that iOS example doesn't break (again) we should build iOS sample app on CI for each PR etc. Too

### PR DESCRIPTION
**Pull request by hoc081098**
Closes #353 
I have checked it, it worked as expected: https://github.com/hoc081098/FlowRedux/actions/runs/3019841020

### CODE REVIEW

**Comment by sockeqwe** [comment]
Hi, Thanks!

But shouldn't we have `xcodebuild` running somewhere too?

**Comment by hoc081098** [comment]
@sockeqwe I think we should run xcodebuild to make sure ios app works as expected

**Review by gabrielittner — APPROVED** [review]
Looks good to me 👍  Thank you

**Comment by gabrielittner** [comment]
> But shouldn't we have xcodebuild running somewhere too?

The last step that uses `sersoft-gmbh/xcodebuild-action@v2.0.0` does that

**Pull request merged**
